faces/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from faces.views import list, IndexView, results

urlpatterns = [
    url(r'^list/$', list, name='list'),
    url(r'^list/(?P<document_id>[0-9]+)/$', results, name='results'),
    url(r'^$', IndexView.as_view(), name='index'),
    ]

facesproject/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
#from django.conf.urls import patterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^faces/', include('faces.urls')),
    url(r'^$', RedirectView.as_view(url='/faces/list/', permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#urlpatterns = patterns('',
 #                      (r'^', include('faces.urls')),
  #                     ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faces/models.py
# -*- coding: utf-8 -*-
from django.db import models
import os

def user_directory_path(instance, filename):
    return 'documents/%s/%s'% (filename.split(".")[0], filename)

#the video file
class Document(models.Model):
    docfile = models.FileField(upload_to=user_directory_path)
    analyzed = models.BooleanField(default=False)
    v_scoreHappy = models.IntegerField(default=0)
    v_scoreSad = models.IntegerField(default=0)
    v_scoreAngry = models.IntegerField(default=0)
    v_scoreSurprise = models.IntegerField(default=0)

    def __str__(self):
        return self.docfile.url

class Picture(models.Model):
    video_loc = models.ForeignKey(Document, on_delete=models.CASCADE)
    picfile = models.FileField()
    analyzed = models.BooleanField(default=False)
    #the emotion each face has if it has one
    numFaces = models.IntegerField(default=0)
    face1 = models.CharField(max_length=200, null=True, blank=True)
    face2 = models.CharField(max_length=200, null=True, blank=True)
    face3 = models.CharField(max_length=200, null=True, blank=True)
    face4 = models.CharField(max_length=200, null=True, blank=True)
    hasFace = models.BooleanField(default=False)

faces/forms.py
# -*- coding: utf-8 -*-

from django import forms


class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file'
    )

faces/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from .models import Document
from faces.forms import DocumentForm
from django.utils import timezone
from faces.utils import main, grab_frame
import PIL

def list(request):
    # Handle file upload
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = Document(docfile=request.FILES['docfile'])
            newdoc.save()

            # Redirect to the document list after POST
            return HttpResponseRedirect(reverse('results', args=(newdoc.id,)))
            #return render(request, 'index.html', {'ifile':newdoc.docfile.url})
            #return HttpResponseRedirect(reverse('results',args=(newdoc.pk,)))
    else:
        form = DocumentForm()  # A empty, unbound form

    # Load documents for the list page
    documents = Document.objects.all()

    # Render list page with the documents and the form
    return render(
        request,
        'index.html',
        {'documents': documents, 'form': form,}
    )


class IndexView(generic.ListView):
    template_name = 'faces/index.html'
    context_object_name = 'latest_upload_list'
    #videofile = "C:/Users/wildcat/facesproject/faces/static/faces/images/jurassicparkf.mp4"
    #grab_frame(videofile, 100)

    def get_queryset(self):
        return None

def results(request, document_id):
    doc = get_object_or_404(Document, pk=document_id)
    ifile = doc.docfile.url

    #analyzes pictures just created and makes sure they won't be analyzed for a second time
    if not doc.analyzed:
        #splits video into picture ~2-4 seconds
        grab_frame(ifile)
        main(doc, 4)
        doc.analyzed = True
        doc.save()

    #for testing purposes
    #videofile = "C:/Users/wildcat/facesproject/faces/static/faces/images/jurassicparkf.mp4"
    #grab_frame(videofile)
    #main(videofile, 4)

    #grabs list of all Documents
    documents = Document.objects.all()
    #unbound form
    form = DocumentForm()
    return render(request, 'index.html', {'documents':documents, 'form':form, 'ifile':doc})

faces/templates/faces/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="upload image file and output emotion person is feeling">
  <meta name="author" content="Jimmy O'Hara and Dan Sullivan">
  <link rel="icon" href="{% static 'faces/images/favicon.ico' %}">

  <title>Faces</title>
  <link href="{% static 'faces/flexcarousel/flexslider.css' %}" rel="stylesheet" type="text/css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'faces/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
  <!-- Bootstrap theme -->
  <link href="{% static 'faces/bootstrap-theme.css' %}" rel="stylesheet" type="text/css">
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->

  <!-- Custom styles for this template -->

  <link href="{% static 'faces/theme.css' %}" rel="stylesheet" type="text/css">

  <!--<link href="{% static 'faces/owl.carousel.css' %}" rel="stylesheet" type="text/css">-->
  <!--<link href="{% static 'faces/owl.theme.css' %}" rel="stylesheet" type="text/css">-->

  <!--<link href="{% static 'faces/prettify.css' %}" rel="stylesheet" type="text/css">-->

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <!--<script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.min.js">\x3C/script>')</script>-->
  <script src="{% static 'faces/js/jquery.flexslider.js' %}"></script>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <!--<script type="text/javascript" charset="utf-8">-->
  <!--$(window).on('load',function() {-->
  <!--$('.flexslider').flexslider();-->
  <!--});-->
  <!--</script>-->
  <script type="text/javascript">

$(window).on('load', function() {
  // The slider being synced must be initialized first
  $('#carousel').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    itemWidth: 210,
    itemMargin: 5,
    asNavFor: '#slider'
  });

  $('#slider').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: false,
    slideshow: false,
    sync: "#carousel"
  });
});


  </script>


</head>

<body>

<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url "list" %}">Faces</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url "list" %}">Home</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="container theme-showcase" role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <h1>Faces</h1>

    <p>Outputs emotion face feels. Can be Joy, Sorrow, Anger, Surprise</p>
  </div>
  <div class="page-header">
    <h1>Upload file with face</h1>
  </div>
  <div class="row">
    <div class="col-md-4">
      <form action="{% url "list" %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <p>{{ form.non_field_errors }}</p>

      <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>

      <p>
        {{ form.docfile.errors }}
        {{ form.docfile }}
      </p>

      <p><input type="submit" value="Upload"/></p>
      </form>
      {% if result %}
      <blockquote>The person in the picture is most likely feeling: {{ result }}</blockquote>
      {% endif %}
    </div>
    <div class="col-md-6">
      {% if ifile %}
      <!-- <img src="{{ ifile }}" class="img-rounded" alt="Upload Image"> -->
      <video width="320" height="240" controls>
        <source src="{{ ifile.docfile.url }}" type="video/mp4">
      </video>
      <blockquote>This video has a Joy score of: {{ ifile.v_scoreHappy }}</blockquote>
      <blockquote>This video has an Anger score of: {{ ifile.v_scoreAngry }}</blockquote>
      <blockquote>This video has a Sorrow score of: {{ ifile.v_scoreSad }}</blockquote>
      <blockquote>This video has a Surprise score of: {{ ifile.v_scoreSurprise }}</blockquote>
      <div id="slider" class="flexslider">
        <ul class="slides">
          {% for picture in ifile.picture_set.all %}
          {% if picture.numFaces >= 1 %}
          <li>
          <img src="{{ picture.picfile.url }}">
          <blockquote>Person 1 is feeling: {{ picture.face1 }}</blockquote>
          {% endif %}
          {% if picture.numFaces >= 2 %}
          <blockquote>Person 2 is feeling: {{picture.face2 }}</blockquote>
          {% endif %}
          {% if picture.face3 %}
          <blockquote>Person 3 is feeling: {{picture.face3 }}</blockquote>
          {% endif %}
          {% if picture.face4 %}
          <blockquote>Person 4 is feeling: {{picture.face4 }}</blockquote>
          {% endif %}
          </li>
          {% endfor %}
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out001.png' %}"/>-->
          <!--</li>-->
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out002.png' %}"/>-->
          <!--</li>-->
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out003.png' %}"/>-->
          <!--</li>-->
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out004.png' %}"/>-->
          <!--</li>-->
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out005.png' %}"/>-->
          <!--</li>-->
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out006.png' %}"/>-->
          <!--</li>-->
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out007.png' %}"/>-->
          <!--</li>-->
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out008.png' %}"/>-->
          <!--</li>-->
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out009.png' %}"/>-->
          <!--</li>-->
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out010.png' %}"/>-->
          <!--</li>-->
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out011.png' %}"/>-->
          <!--</li>-->
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out012.png' %}"/>-->
          <!--</li>-->
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out013.png' %}"/>-->
          <!--</li>-->
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out014.png' %}"/>-->
          <!--</li><li>-->
          <!--<img src="{% static 'faces/images/out015.png' %}"/>-->
        <!--</li><li>-->
          <!--<img src="{% static 'faces/images/out016.png' %}"/>-->
        <!--</li>-->
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out017.png' %}"/>-->
          <!--</li>-->
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out018.png' %}"/>-->
          <!--</li>-->
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out019.png' %}"/>-->
          <!--</li>-->
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out020.png' %}"/>-->
          <!--</li>-->
          <!--<li>-->
            <!--<img src="{% static 'faces/images/out021.png' %}"/>-->
          <!--</li>-->
        </ul>
      </div>

        <div id="carousel" class="flexslider">
          <ul class="slides">
            {% for picture in ifile.picture_set.all %}
            {% if picture.numFaces >= 1 %}
            <li>
              <img src="{{ picture.picfile.url }}"/>
            </li>
            {% endif %}
            {% endfor %}
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out001.png' %}"/>-->
            <!--</li>-->
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out002.png' %}"/>-->
            <!--</li>-->
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out003.png' %}"/>-->
            <!--</li>-->
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out004.png' %}"/>-->
            <!--</li>-->
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out005.png' %}"/>-->
            <!--</li>-->
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out006.png' %}"/>-->
            <!--</li>-->
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out007.png' %}"/>-->
            <!--</li>-->
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out008.png' %}"/>-->
            <!--</li>-->
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out009.png' %}"/>-->
            <!--</li>-->
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out010.png' %}"/>-->
            <!--</li>-->
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out011.png' %}"/>-->
            <!--</li>-->
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out012.png' %}"/>-->
            <!--</li>-->
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out013.png' %}"/>-->
            <!--</li>-->
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out014.png' %}"/>-->
            <!--</li><li>-->
            <!--<img src="{% static 'faces/images/out015.png' %}"/>-->
          <!--</li><li>-->
            <!--<img src="{% static 'faces/images/out016.png' %}"/>-->
          <!--</li>-->
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out017.png' %}"/>-->
            <!--</li>-->
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out018.png' %}"/>-->
            <!--</li>-->
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out019.png' %}"/>-->
            <!--</li>-->
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out020.png' %}"/>-->
            <!--</li>-->
            <!--<li>-->
              <!--<img src="{% static 'faces/images/out021.png' %}"/>-->
            <!--</li>-->
            <!-- items mirrored twice, total of 12 -->
          </ul>
        </div>
      {% endif %}
    </div>
  </div>

  <!--<video width="320" height="240" controls>-->
    <!--<source src="{% static 'faces/images/jurassicparkf.mp4' %}" type="video/mp4">-->
  <!--</video>-->

  {% if documents %}
  <ul>
    {% for document in documents %}
    <!--<li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li> -->
    <li><a href="{% url "results" document.id %}">{{ document.docfile.name }} Happy: {{ document.v_scoreHappy }}  Sad: {{ document.v_scoreSad }} Surprise: {{ document.v_scoreSurprise }}  Angry: {{ document.v_scoreAngry }}</a></li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No documents.</p>
  {% endif %}


</div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>-->
    <!--<script>window.jQuery || document.write('<script src="js/jquery.min.js"><\/script>')</script>-->
    <script src="{% static 'faces/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'faces/js/docs.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'faces/js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

faces/templates/faces/list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Minimal Django File Upload Example</title>
    </head>

    <body>
        <!-- List of uploaded documents -->
        {% if documents %}
            <ul>
                {% for document in documents %}
                    <li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No documents.</p>
        {% endif %}

        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url "list" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>

            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>

            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p>

            <p><input type="submit" value="Upload"/></p>
        </form>
    </body>

</html>